name: update deno modules using uud

inputs:
  github_token:
    description: "github token"
    required: true

runs:
  using: composite
  steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: "1.x"
    - name: Update dependencies
      run: |
        deno run -A https://deno.land/x/udd@0.8.2/main.ts **/deps.ts
      env:
        NO_COLOR: 1
    - name: Read ../output.txt
      id: log
      uses: juliangruber/read-file-action@v1
      with:
        path: ../output.txt
    - name: Diff check
      id: diff
      run: |
        echo "content=$(git diff --name-only | grep ts)" >> $GITHUB_OUTPUT
    - name: Commit changes
      if: ${{ steps.diff.outputs.content != '' }}
      run: |
        git config user.name '${{ github.actor }}'
        git config user.email '${{ github.actor }}@users.noreply.github.com'
        git commit -a -F- <<EOM
        :package: Update Deno dependencies

        Update dependencies by udd:

        ${{ steps.log.outputs.content }}

        EOM
    - uses: peter-evans/create-pull-request@v3
      if: ${{ steps.diff.outputs.content != '' }}
      with:
        title: ":package: Update Deno dependencies"
        body: |
          ```
          ${{ steps.log.outputs.content }}
          ```
        labels: automation
        branch: automation/update-dependencies
        delete-branch: true
        token: input.github_token
