name: update deno modules
description: update deno modules using uud

runs:
  using: composite
  steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: "1.x"
    - name: Update dependencies
      shell: bash
      run: |
        deno run -A https://deno.land/x/udd@0.8.2/main.ts **/deps.ts > ../output.txt
      env:
        NO_COLOR: "1"
    - name: Read ../output.txt
      id: log
      uses: juliangruber/read-file-action@v1
      with:
        path: ../output.txt
    - name: Diff check
      id: diff
      shell: bash
      run: |
        echo "content=$(git diff --name-only | grep ts)" >> $GITHUB_OUTPUT
    - name: Commit changes
      if: steps.diff.outputs.content != ''
      shell: bash
      run: |
        git config user.name '${{ github.actor }}'
        git config user.email '${{ github.actor }}@users.noreply.github.com'
        git commit -a -F- <<EOM
        :package: Update Deno dependencies

        Update dependencies by udd:

        ${{ steps.log.outputs.content }}

        EOM
